[tool.pytest.ini_options]
addopts = [
    "--alluredir=allure-reports",
    "--strict-markers",
    "--strict-config",
    "-vs"
]
markers = [
    "wip"
]


[tool.black]
line-length=79
target-version=['py311']
extend-exclude = '''
/(
  # Env files
  venv
)/
'''
