from src.locators.sample_app_locators import SampleAppPageLocators
from src.locators.overlapped_element_locators import OverlappedElementLocators
from src.locators.load_delay_locators import LoadDelayLocators
from src.locators.text_input_locators import TextInputLocators
from src.locators.click_locators import ClickLocators
